SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

CREATE TABLE IF NOT EXISTS `flight_request` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `valid_from_date` timestamp NOT NULL DEFAULT '2016-01-01 00:00:00',
  `valid_to_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `user_id` bigint(20) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

INSERT INTO `flight_request` (`id`, `valid_from_date`, `valid_to_date`, `user_id`) VALUES
(1,'2016-02-01 01:00:00','2016-11-01 23:00:00',3),
(2,'2016-02-09 23:00:00','2016-12-14 23:00:00',3);

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
